### ISSUE TITLE
"Open changesets by owner" Gerrit report broken since June 2015

### ISSUE THREAD

**Issue by mzmcbride** [mzmcbride/gerrit-reports#13]
https://www.mediawiki.org/w/index.php?title=Gerrit/Reports/Open_changesets_by_owner&action=history

The "Open changesets by owner" Gerrit report last updated on June 20, 2015. :-(

The likely culprit is 5fcbbfb24094d857e10c44089115558a7677af82, but this commit is attributed to `Author: tools.gerrit-reports <tools.gerrit-reports@tools-bastion-01.tools.eqiad.wmflabs>`. Hmmm.

**Comment by mzmcbride** [comment]
I fixed this issue in de87dac0820a9c484c52de16b3b3a72db883ed6d.

I assume @nemobis is responsible for 5fcbbfb24094d857e10c44089115558a7677af82, but I won't leave this issue open to [ht]aunt him.

I manually ran the fixed script from `tools-bastion-05` and <https://www.mediawiki.org/w/index.php?title=Gerrit/Reports/Open_changesets_by_owner&action=history> has now been updated.

**Comment by nemobis** [comment]
Thanks
