### ISSUE TITLE
Add link to repo description

### ISSUE THREAD

**Issue by waldyrious** [mzmcbride/gerrit-reports#9]
In the short description (not the readme, I mean in the area at the top of the repo page, where it currently says simply "Gerrit reports") there's an option to add an url. I suggest linking to https://www.mediawiki.org/wiki/Gerrit/Navigation#Reports on it (and perhaps, while you're at it, changing the description to something more explicit, like "Gerrit reports – Wikimedia code review stats").

**Comment by nemobis** [comment]
I used some hideous markdown even though it's not a .md file. :O I'm also ok with using another syntax of moving the file if you want the syntax rendered here, feel free.
